### ISSUE TITLE
Any comparison with RMSNorm?

### ISSUE THREAD

**Issue by radarFudan** [xinghaochen/SLAB#1]
Thank you for the very nice work. 

I’m currently exploring various normalization techniques and noticed that RMSNorm is generally considered a less computationally intensive alternative compared to Layer Norm. Given that I’m not deeply familiar with the intricacies of these normalization methods, I would appreciate some clarification on how your method compares in terms of efficiency with RMSNorm.

Could you provide some insights or benchmarks on this? Any information you can share would be greatly helpful.

**Comment by xinghaochen** [comment]
Thanks for the question. LLaMA adopts RMSNorm and utilizing our mthod to replace it with BatchNorm still obtains better efficiency, as shown in the experiment section of our paper.
