### ISSUE TITLE
About total step in your code

### ISSUE THREAD

**Issue by Zhaohuii-Wang** [xinghaochen/SLAB#3]
Thank you very much for your work, this work should be very scalable! 
I have observed that the superparameter step (total step) of linearnorm in the code seems to be only related to the model, but not to the dataset, whether it is because these are fixed by your implementation. 
`linearnorm = partial(LinearNorm, norm1=ln, norm2=RepBN, step=60000)` in slab_swin
`linearnorm = partial(LinearNorm, norm1=nn.LayerNorm, norm2=RepBN, step=120000)` in slab_cswin
`linearnorm = partial(LinearNorm, norm1=ln, norm2=RepBN)` in others
Should I set my total step to `epoch * len (train_dataloader)` in linearnorm when I train it? or any tricks here?

**Comment by guojialong1** [comment]
The total step should make sure that LN is coverted to BN before the end of training, so we set the value less than ```epoch * len (train_dataloader)```. This hyperparameter generally needs to be large enough to ensure stable training. In addition, the hyperparameter can be adjusted appropriately to achieve higher model accuracy. The hyperparameters given by our code are set empirically, and in most of our experiments, It has little impact on the accuracy when the total step is large enough.
