### ISSUE TITLE
参数warm，iter和total_step

### ISSUE THREAD

**Issue by sdreamforchen** [xinghaochen/SLAB#5]
大佬，恕我太菜。  没有找到您如何将warm，iter和total_step传递到函数内的。仅看见norm
1、norm2和dim的传递

**Comment by guojialong1** [comment]
在分类任务里面，warm这个参数并没有使用，因此默认都是初始值。iter和total_step在未额外设置的情况下采用prepbn.py文件中的默认设置，其余在各个模型文件中会有设置。

**Comment by sdreamforchen** [comment]
感谢🙏🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月29日(周一) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xinghaochen/SLAB] 参数warm，iter和total_step (Issue #5)




 
在分类任务里面，warm这个参数并没有使用，因此默认都是初始值。iter和total_step在未额外设置的情况下采用prepbn.py文件中的默认设置，其余在各个模型文件中会有设置。
