### ISSUE TITLE
移植到其他算法上出现了损失发散的情况

### ISSUE THREAD

**Issue by LittleRain626** [xinghaochen/SLAB#9]
我使用LinearNorm替换了代码中的LayerNorm，但是出现了损失发散的情况，请问一下这个是什么原因呢？

**Comment by guojialong1** [comment]
移植到其它算法的时候，BN的引入可能导致损失不收敛的情况。如果损失发散，可以尝试增大LinearNorm的step以及使用warmup。

**Comment by LittleRain626** [comment]
> 移植到其它算法的时候，BN的引入可能导致损失不收敛的情况。如果损失发散，可以尝试增大LinearNorm的step以及使用warmup。

感谢回复！这个问题暂时已经解决了。
